theme: jekyll-theme-minimal

# General information for the homepage
title: Jiyin He
description: "Researcher in Information Retrieval."
contact: jiyinhe[at]gmail[dot]com
socials:
    -
        name: Google Scholar Citations
        url: https://scholar.google.com/citations?user=F-8qMNEAAAAJ
    -
        name: DBLP 
        url: http://dblp.uni-trier.de/pers/hd/h/He:Jiyin
    -
        logo: <img src="https://static.licdn.com/scds/common/u/img/webpromo/btn_profile_bluetxt_80x15.png" width="100" height="20" border="0" alt="View Jiyin He's profile on LinkedIn">
        name: LinkedIn
        url: https://nl.linkedin.com/in/jiyinhe

       
