theme: jekyll-theme-architect

include: [ _pages ]

# Variables used in pages
title: Jiyin He
description: "Research and random thoughts on information and life"
research_profile:
    -
        name: Google Scholar Citations
        url: https://scholar.google.com/citations?user=F-8qMNEAAAAJ
    -
        name: DBLP 
        url: http://dblp.uni-trier.de/pers/hd/h/He:Jiyin

socials:
    -
        logo: <img src="/assets/img/In-China-2C-34px-TM.png" height="25" alt="LinkedIn profile">
        name: LinkedIn
        url: https://nl.linkedin.com/in/jiyinhe

publication_types: 
    -
        type: "Conference paper"
        name: "Conference papers"
        id: "conf"

    -
        type: "Journal article"
        name: "Journal articles"
        id: "jour"

    -
        type: "Book chapter"
        name: "Book chapters"
        id: "bcha"
    -
        type: "Eds."
        name: "Eds."
        id: "eds"
    -
        type: "Workshop paper"
        name: "Workshop papers"
        id: "work"
    -
        type: "Evaluation campaigns (TREC)"
        name: "Evaluation campaigns"
        id: "eval"
    -
        type: "PhD dissertation"
        name: "PhD dissertation"
        id: "phd"

